[build]
  base = "fyf-app"
  command = "npm run build"
  publish = "fyf-app/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd fyf-app && npm run dev"
  port = 3000
  publish = "fyf-app/.next"
